### PR TITLE
Add transaction signign for ZIP 143

### PR DESCRIPTION
**Pull request by wo01**

### CODE REVIEW

**Comment by karel-3d** [comment]
I am not testing if this is actually working - it should however not break anything. So merging

**Comment by nettts** [comment]
This broke everything.

**Comment by karel-3d** [comment]
...ok. Does this PR fix it?

https://github.com/karel-3d/bitcoinjs-lib/pull/7

**Comment by karel-3d** [comment]
I will probably edit this library to not have any code that we use in Trezor web wallet - there is a lot of code that we don't use and don't test...

**Comment by karel-3d** [comment]
Also, there will be a big change soon that will replace all amounts from numbers to bigint (because of some altcoins that have numbers bigger than 2^53), which will break all third party dependencies anyway

**Comment by nettts** [comment]
@karel-3d

Yeah it does after the bytelength it does. Contributor fixed after I mentioned it. 

For some reason reverting sets setOverwinter to an array and or a function. Caught that before it was merged again and contributor fixed it.

Anyways thanks for the response. Look forward to where this goes.

Also what do you mean by depends? Like if we depend on this library for node-stratum-pool.. will that change break current functionality? Thanks.

**Comment by karel-3d** [comment]
Just for information

After some testing, I will deprecate this library and we will start using this one

https://github.com/trezor/bitcoinjs-trezor

Unlike this one, bitcoinjs-trezor has only the functions that we use in Trezor web wallet, but does NOT have functions that we don't use. Specifically, it does not have transaction signing, since that happens in Trezor.

You are free to fork this library

**Pull request merged**
